openapi: 3.0.2
info:
  title: Acquirer APIs adapter
  version: 1.0.0
  description: APIs to receive external authorizations from Banklo
paths:
  /transactions:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request-transaction'
        required: true
      tags:
        - transactions
      responses:
        '201':
          $ref: '#/components/responses/201-success'
        '400':
          $ref: '#/components/responses/400-bad-request'
        '401':
          $ref: '#/components/responses/401-unauthorized'
        '403':
          $ref: '#/components/responses/401-unauthorized'
        '500':
          $ref: '#/components/responses/500-unavailable'
      operationId: create-transaction
  '/transactions/{id}/cancellation':

    post:
      parameters:
        - in: path
          name: id
          schema:
            $ref: '#/components/schemas/id'
          required: true
          description: transaction id to apply operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request-cancellation'
        required: true
      tags:
        - transactions
      responses:
        '201':
          $ref: '#/components/responses/201-success'
        '400':
          $ref: '#/components/responses/400-bad-request'
        '401':
          $ref: '#/components/responses/401-unauthorized'
        '403':
          $ref: '#/components/responses/403-forbidden'
        '500':
          $ref: '#/components/responses/500-unavailable'
      operationId: request-cancellation
  '/transactions/{id}/reversal':
    post:
      parameters:
        - in: path
          name: id
          schema:
            $ref: '#/components/schemas/id'
          required: true
          description: transaction id to apply operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request-reversal'
        required: true
      tags:
        - transactions
      responses:
        '201':
          $ref: '#/components/responses/201-success'
        '400':
          $ref: '#/components/responses/400-bad-request'
        '401':
          $ref: '#/components/responses/401-unauthorized'
        '403':
          $ref: '#/components/responses/403-forbidden'
        '500':
          $ref: '#/components/responses/500-unavailable'
      operationId: request-reversal
components:
  schemas:
    id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      minLength: 36
      maxLength: 36
      example: 4cb0b69e-e4bd-46f6-b011-8cd5d2d3964b
    currency_code:
      type: string
      minLength: 3
      maxLength: 3
      example: EUR
      description: |
        The currency code from ISO 4217 find more at https://en.wikipedia.org/wiki/ISO_4217
    country_code:
      type: string
      description: |
        The country code from ISO 3166 find more at https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
      minLength: 3
      maxLength: 3
      example: ARG
    request-transaction:
      title: request-transaction
      description: ''
      type: object
      properties:
        authorization_code:
          $ref: '#/components/schemas/id'
        acquirer_code:
          $ref: '#/components/schemas/id'
        merchant_code:
          $ref: '#/components/schemas/id'
        currency_code:
          $ref: '#/components/schemas/currency_code'
        transaction_data:
          type: object
          properties:
            with_password:
              type: boolean
            transaction_type:
              type: string
            amount:
              type: number
            transaction_id:
              $ref: '#/components/schemas/id'
            card_id:
              $ref: '#/components/schemas/id'
        country_code:
          $ref: '#/components/schemas/country_code'
      example:
        authorization_code: b7679972-0c02-11ed-870e-0bd9fad36067
        acquirer_code: b7679a80-0c02-11ed-870f-7369662850ea
        merchant_code: b7679aa8-0c02-11ed-8710-13a200d59031
        currency_code: b7679b02-0c02-11ed-8713-0f4e1eec6501
        transaction_data:
          with_password: true
          transaction_type: credit
          amount: 231
          id: b7679b02-0c02-11ed-8713-0f4e1eec6501
        country_code: BRA
    request-reversal:
      title: request-reversal
      description: ''
      type: object
      properties:
        authorization_code:
          $ref: '#/components/schemas/id'
        acquirer_code:
          $ref: '#/components/schemas/id'
        merchant_code:
          $ref: '#/components/schemas/id'
        currency_code:
          $ref: '#/components/schemas/currency_code'
        transaction_data:
          type: object
          properties:
            transaction_type:
              type: string
            transaction_id:
              $ref: '#/components/schemas/id'
            card_id:
              $ref: '#/components/schemas/id'
        country_code:
          $ref: '#/components/schemas/country_code'
      example:
        authorization_code: b7679972-0c02-11ed-870e-0bd9fad36067
        acquirer_code: b7679a80-0c02-11ed-870f-7369662850ea
        merchant_code: b7679aa8-0c02-11ed-8710-13a200d59031
        currency_code: b7679b02-0c02-11ed-8713-0f4e1eec6501
        transaction_data:
          transaction_type: reversal
          transaction_id: a225edb0-0c03-11ed-ae03-c3d8f097c2ff
        country_code: BRA
    request-cancellation:
      title: request-cancellation
      description: ''
      type: object
      properties:
        authorization_code:
          $ref: '#/components/schemas/id'
        acquirer_code:
          $ref: '#/components/schemas/id'
        merchant_code:
          $ref: '#/components/schemas/id'
        currency_code:
          $ref: '#/components/schemas/currency_code'
        transaction_data:
          type: object
          properties:
            transaction_type:
              type: string
            transaction_id:
              $ref: '#/components/schemas/id'
            card_id:
              $ref: '#/components/schemas/id'
        country_code:
          $ref: '#/components/schemas/country_code'
      example:
        authorization_code: b7679972-0c02-11ed-870e-0bd9fad36067
        acquirer_code: b7679a80-0c02-11ed-870f-7369662850ea
        merchant_code: b7679aa8-0c02-11ed-8710-13a200d59031
        currency_code: b7679b02-0c02-11ed-8713-0f4e1eec6501
        transaction_data:
          transaction_type: cancellation
          transaction_id: a225edb0-0c03-11ed-ae03-c3d8f097c2ff
        country_code: BRA
    response-transactions:
      title: response-transactions
      description: ''
      type: object
      required:
        - transaction_id
        - registered_at
      properties:
        transaction_id:
          $ref: '#/components/schemas/id'
        registered_at:
          format: date-time
          type: string
      example:
        transaction_id: a200609c-0c06-11ed-9205-73f6505a2b35
        registered_at: '2022-07-25T10:44:18+0000'
    generic-error:
      title: generic-error
      description: ''
      type: object
      properties:
        code:
          type: string
        description:
          type: string
      example:
        code: '001'
        description: error message
  responses:
    201-success:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/response-transactions'
      description: ''
    400-bad-request:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic-error'
      description: ''
    401-unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic-error'
      description: ''
    403-forbidden:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic-error'
      description: ''
    500-unavailable:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic-error'
      description: ''
tags:
  -
    name: transactions
    description: Transactions operations